Runtime can be NULL in the database, which we didn't expect
While looking at W6 postcode area:

```
  File "/home/travelinedata/travelinedata/server.py", line 172, in _runtime
    "h": float(runtime_sec) / 3600,
TypeError: float() argument must be a string or a number, not 'NoneType'
```